// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1dv22B_Hk98Quyv0l2mRz3Bb29-bGVHg',
    appId: '1:454921925709:web:31ebe6b92ac29703579804',
    messagingSenderId: '454921925709',
    projectId: 'visitor-entry-app-1a330',
    authDomain: 'visitor-entry-app-1a330.firebaseapp.com',
    storageBucket: 'visitor-entry-app-1a330.firebasestorage.app',
    measurementId: 'G-0Z054WQ6R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtzXw1BT4gY8w94cMJlIpJpSLiAhfjdZ8',
    appId: '1:454921925709:android:e1d83bd0bbf725c8579804',
    messagingSenderId: '454921925709',
    projectId: 'visitor-entry-app-1a330',
    storageBucket: 'visitor-entry-app-1a330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1ZMQRqhSxyohXmiCTz5yBuM_CoXyV7I',
    appId: '1:454921925709:ios:0699d0f109f97550579804',
    messagingSenderId: '454921925709',
    projectId: 'visitor-entry-app-1a330',
    storageBucket: 'visitor-entry-app-1a330.firebasestorage.app',
    iosBundleId: 'com.example.visitorEntryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1ZMQRqhSxyohXmiCTz5yBuM_CoXyV7I',
    appId: '1:454921925709:ios:0699d0f109f97550579804',
    messagingSenderId: '454921925709',
    projectId: 'visitor-entry-app-1a330',
    storageBucket: 'visitor-entry-app-1a330.firebasestorage.app',
    iosBundleId: 'com.example.visitorEntryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1dv22B_Hk98Quyv0l2mRz3Bb29-bGVHg',
    appId: '1:454921925709:web:2bde77e380b42f4a579804',
    messagingSenderId: '454921925709',
    projectId: 'visitor-entry-app-1a330',
    authDomain: 'visitor-entry-app-1a330.firebaseapp.com',
    storageBucket: 'visitor-entry-app-1a330.firebasestorage.app',
    measurementId: 'G-0ZXKHJQK29',
  );
}
